### PR TITLE
Move to 3.0 Preview 6 SDK and 2.1.11 runtime

### PR DESCRIPTION
**Pull request by dougbu**
/cc @riarenas

### CODE REVIEW

**Comment by dougbu** [comment]
Consistent failure in the Linux Debug test job but I can't find anything in the artifacts that helps. @chcosta @jonfortescue @riarenas how should I dig deeper than the following?
image

**Comment by jonfortescue** [comment]
@dougbu looks like that queue is deadlettered. Will push up a change to stop using that queue.

**Comment by dougbu** [comment]
@jonfortescue will you push that change into my branch (which is in a fork)? Or, should we just merge this change now?

@jonfortescue or @riarenas if this is ready to go, please merge. I don't have push permissions in this repo.

**Comment by jonfortescue** [comment]
@dougbu Ah, just realized this is a fork. I will merge these changes now and then fix the deadlettering as part of a future PR.

**Pull request merged**
