### PR TITLE
Rename NuGet.Config to NuGet.config

### PR DESCRIPTION
**Pull request by jonfortescue**
So will this mean that every time a repo consumes Maestro they just have to make this rename change?

(note: i'm fairly certain that most of these words are wrong)

### CODE REVIEW

**Comment by chcosta** [comment]
Why is the DevOps ci gate not firing for this pr?

**Comment by jonfortescue** [comment]
@chcosta ...that is an excellent question

**Comment by chcosta** [comment]
It's because you're merging into AddHelixJob, not into master.  we need this fixed in master, we need builds flowing ASAP

**Comment by jonfortescue** [comment]
shoot. I will fix.

**Pull request closed without merging**
